configuration: Release
init:
  - git config --global core.autocrlf true
before_build:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - nuget restore
build_script:
  - build.cmd 
after_build:
  - ps: Write-Host "build DONE,Start UnitTest"
  - ps: Write-Host "当前目录下的文件："
  - cmd: dir /a *
  - cmd: cd C:/projects/fileupload/FileUpload/bin
  - cmd: dir /a *
  - cmd: cd C:/projects/fileupload/FileUpload.Tests/bin
  - cmd: dir /a *
  - vstest.console.exe /logger:Appveyor C:/projects/fileupload/FileUpload/FileUpload.Tests/bin/FileUpload.Tests.dll
  - vstest.console.exe /logger:Appveyor /Platform:x86 /Framework:Framework45 C:/projects/fileupload/FileUpload/FileUpload.Tests/bin/FileUpload.Tests.dll /UseVsixExtensions:true /InIsolation /TestCaseFilter:"Priority=1"
  - cmd: cd C:/projects/fileupload/FileUpload/FileUpload.xUnit.Tests/bin
  - cmd: dir /a *
  - xunit.console C:/projects/fileupload/FileUpload/FileUpload.xUnit.Tests/bin/FileUpload.xUnit.Tests.dll
clone_depth: 1
test:
  assemblies:
    - '**\*.FileUpload.dll'
deploy: off