init:
  - git config --global core.autocrlf true
build_script:
  - build.cmd --quiet verify
clone_depth: 1
test:
  categories:
    only:
      - BigFileUploadController
      - FileBaseController
	  - FileUploadController
      - HomeController
	  - ImagUploadController
deploy: off